FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/main ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

COPY --from=builder /app/configs/docker.yaml /app/configs/config.yaml
COPY --from=builder /app/migrations/2_create_table_house.sql /app/migrations/2_create_table_house.sql

EXPOSE 9002

CMD ["./main"]
