modelog: debug

postgresdb:
  host: "postgres"
  port: 5432
  user: "admin"
  password: "admin"
  name: "home-service"

redisdb:
  host: "redis:6379"
  port: 6379
  name: "name"

grpc:
  port: 9002
  authaddress: "auth-service:9001"

jet:
  address: "nats://nats:4222"
  subject: "house"
  name: "subscriber"
