// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: api/home/create-house.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Year      int32  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Developer string `protobuf:"bytes,3,opt,name=developer,proto3" json:"developer,omitempty"`
}

func (x *CreateHouseRequest) Reset() {
	*x = CreateHouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_home_create_house_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseRequest) ProtoMessage() {}

func (x *CreateHouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_home_create_house_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseRequest) Descriptor() ([]byte, []int) {
	return file_api_home_create_house_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHouseRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateHouseRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateHouseRequest) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

type CreateHouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Year      int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Developer string `protobuf:"bytes,4,opt,name=developer,proto3" json:"developer,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
}

func (x *CreateHouseResponse) Reset() {
	*x = CreateHouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_home_create_house_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseResponse) ProtoMessage() {}

func (x *CreateHouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_home_create_house_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseResponse.ProtoReflect.Descriptor instead.
func (*CreateHouseResponse) Descriptor() ([]byte, []int) {
	return file_api_home_create_house_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHouseResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateHouseResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateHouseResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateHouseResponse) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *CreateHouseResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateHouseResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_home_create_house_proto protoreflect.FileDescriptor

var file_api_home_create_house_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2d, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68,
	0x6f, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x22, 0xb1, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f,
	0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_home_create_house_proto_rawDescOnce sync.Once
	file_api_home_create_house_proto_rawDescData = file_api_home_create_house_proto_rawDesc
)

func file_api_home_create_house_proto_rawDescGZIP() []byte {
	file_api_home_create_house_proto_rawDescOnce.Do(func() {
		file_api_home_create_house_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_home_create_house_proto_rawDescData)
	})
	return file_api_home_create_house_proto_rawDescData
}

var file_api_home_create_house_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_home_create_house_proto_goTypes = []any{
	(*CreateHouseRequest)(nil),  // 0: home.CreateHouseRequest
	(*CreateHouseResponse)(nil), // 1: home.CreateHouseResponse
}
var file_api_home_create_house_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_home_create_house_proto_init() }
func file_api_home_create_house_proto_init() {
	if File_api_home_create_house_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_home_create_house_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateHouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_home_create_house_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateHouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_home_create_house_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_home_create_house_proto_goTypes,
		DependencyIndexes: file_api_home_create_house_proto_depIdxs,
		MessageInfos:      file_api_home_create_house_proto_msgTypes,
	}.Build()
	File_api_home_create_house_proto = out.File
	file_api_home_create_house_proto_rawDesc = nil
	file_api_home_create_house_proto_goTypes = nil
	file_api_home_create_house_proto_depIdxs = nil
}
