// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: api/home/flats-in-house.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_created      Status = 0
	Status_approved     Status = 1
	Status_declined     Status = 2
	Status_onModeration Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "created",
		1: "approved",
		2: "declined",
		3: "onModeration",
	}
	Status_value = map[string]int32{
		"created":      0,
		"approved":     1,
		"declined":     2,
		"onModeration": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_home_flats_in_house_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_home_flats_in_house_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_home_flats_in_house_proto_rawDescGZIP(), []int{0}
}

type GetFlatsInHouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFlatsInHouseRequest) Reset() {
	*x = GetFlatsInHouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_home_flats_in_house_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlatsInHouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlatsInHouseRequest) ProtoMessage() {}

func (x *GetFlatsInHouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_home_flats_in_house_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlatsInHouseRequest.ProtoReflect.Descriptor instead.
func (*GetFlatsInHouseRequest) Descriptor() ([]byte, []int) {
	return file_api_home_flats_in_house_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlatsInHouseRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFlatsInHouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flats []*Flat `protobuf:"bytes,1,rep,name=flats,proto3" json:"flats,omitempty"`
}

func (x *GetFlatsInHouseResponse) Reset() {
	*x = GetFlatsInHouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_home_flats_in_house_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlatsInHouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlatsInHouseResponse) ProtoMessage() {}

func (x *GetFlatsInHouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_home_flats_in_house_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlatsInHouseResponse.ProtoReflect.Descriptor instead.
func (*GetFlatsInHouseResponse) Descriptor() ([]byte, []int) {
	return file_api_home_flats_in_house_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlatsInHouseResponse) GetFlats() []*Flat {
	if x != nil {
		return x.Flats
	}
	return nil
}

type Flat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseId int32  `protobuf:"varint,2,opt,name=house_id,proto3" json:"house_id,omitempty"`
	Price   int32  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Rooms   int32  `protobuf:"varint,4,opt,name=rooms,proto3" json:"rooms,omitempty"`
	Status  string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Flat) Reset() {
	*x = Flat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_home_flats_in_house_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flat) ProtoMessage() {}

func (x *Flat) ProtoReflect() protoreflect.Message {
	mi := &file_api_home_flats_in_house_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flat.ProtoReflect.Descriptor instead.
func (*Flat) Descriptor() ([]byte, []int) {
	return file_api_home_flats_in_house_proto_rawDescGZIP(), []int{2}
}

func (x *Flat) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flat) GetHouseId() int32 {
	if x != nil {
		return x.HouseId
	}
	return 0
}

func (x *Flat) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Flat) GetRooms() int32 {
	if x != nil {
		return x.Rooms
	}
	return 0
}

func (x *Flat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_home_flats_in_house_proto protoreflect.FileDescriptor

var file_api_home_flats_in_house_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x66, 0x6c, 0x61, 0x74, 0x73,
	0x2d, 0x69, 0x6e, 0x2d, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x68, 0x6f, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x74,
	0x73, 0x49, 0x6e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x74, 0x73, 0x49, 0x6e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x66, 0x6c,
	0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x6f, 0x6d, 0x65,
	0x2e, 0x46, 0x6c, 0x61, 0x74, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x74, 0x73, 0x22, 0x76, 0x0a, 0x04,
	0x46, 0x6c, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2a, 0x43, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x65, 0x63,
	0x6c, 0x69, 0x6e, 0x65, 0x64, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x6f, 0x6e, 0x4d, 0x6f, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x03, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f,
	0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_home_flats_in_house_proto_rawDescOnce sync.Once
	file_api_home_flats_in_house_proto_rawDescData = file_api_home_flats_in_house_proto_rawDesc
)

func file_api_home_flats_in_house_proto_rawDescGZIP() []byte {
	file_api_home_flats_in_house_proto_rawDescOnce.Do(func() {
		file_api_home_flats_in_house_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_home_flats_in_house_proto_rawDescData)
	})
	return file_api_home_flats_in_house_proto_rawDescData
}

var file_api_home_flats_in_house_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_home_flats_in_house_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_home_flats_in_house_proto_goTypes = []any{
	(Status)(0),                     // 0: home.Status
	(*GetFlatsInHouseRequest)(nil),  // 1: home.GetFlatsInHouseRequest
	(*GetFlatsInHouseResponse)(nil), // 2: home.GetFlatsInHouseResponse
	(*Flat)(nil),                    // 3: home.Flat
}
var file_api_home_flats_in_house_proto_depIdxs = []int32{
	3, // 0: home.GetFlatsInHouseResponse.flats:type_name -> home.Flat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_home_flats_in_house_proto_init() }
func file_api_home_flats_in_house_proto_init() {
	if File_api_home_flats_in_house_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_home_flats_in_house_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlatsInHouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_home_flats_in_house_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlatsInHouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_home_flats_in_house_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Flat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_home_flats_in_house_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_home_flats_in_house_proto_goTypes,
		DependencyIndexes: file_api_home_flats_in_house_proto_depIdxs,
		EnumInfos:         file_api_home_flats_in_house_proto_enumTypes,
		MessageInfos:      file_api_home_flats_in_house_proto_msgTypes,
	}.Build()
	File_api_home_flats_in_house_proto = out.File
	file_api_home_flats_in_house_proto_rawDesc = nil
	file_api_home_flats_in_house_proto_goTypes = nil
	file_api_home_flats_in_house_proto_depIdxs = nil
}
