// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenSaver is an autogenerated mock type for the RefreshTokenSaver type
type RefreshTokenSaver struct {
	mock.Mock
}

// SaveRefreshToken provides a mock function with given fields: ctx, refreshToken, uid
func (_m *RefreshTokenSaver) SaveRefreshToken(ctx context.Context, refreshToken string, uid string) error {
	ret := _m.Called(ctx, refreshToken, uid)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, refreshToken, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefreshTokenSaver creates a new instance of RefreshTokenSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenSaver {
	mock := &RefreshTokenSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
