// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RefreshTokenChecker is an autogenerated mock type for the RefreshTokenChecker type
type RefreshTokenChecker struct {
	mock.Mock
}

// CheckRefreshToken provides a mock function with given fields: refreshToken
func (_m *RefreshTokenChecker) CheckRefreshToken(refreshToken string) error {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for CheckRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefreshTokenChecker creates a new instance of RefreshTokenChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenChecker {
	mock := &RefreshTokenChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
