// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRegister is an autogenerated mock type for the UserRegister type
type UserRegister struct {
	mock.Mock
}

// SaveUser provides a mock function with given fields: ctx, email, hashPass, userType
func (_m *UserRegister) SaveUser(ctx context.Context, email string, hashPass []byte, userType string) (string, error) {
	ret := _m.Called(ctx, email, hashPass, userType)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) (string, error)); ok {
		return rf(ctx, email, hashPass, userType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) string); ok {
		r0 = rf(ctx, email, hashPass, userType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = rf(ctx, email, hashPass, userType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRegister creates a new instance of UserRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegister {
	mock := &UserRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
