// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: subscribe-house.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeToHouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SubscribeToHouseRequest) Reset() {
	*x = SubscribeToHouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subscribe_house_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeToHouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToHouseRequest) ProtoMessage() {}

func (x *SubscribeToHouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_house_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToHouseRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToHouseRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_house_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeToHouseRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubscribeToHouseRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SubscribeToHouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeToHouseResponse) Reset() {
	*x = SubscribeToHouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subscribe_house_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeToHouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToHouseResponse) ProtoMessage() {}

func (x *SubscribeToHouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_house_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToHouseResponse.ProtoReflect.Descriptor instead.
func (*SubscribeToHouseResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_house_proto_rawDescGZIP(), []int{1}
}

var File_subscribe_house_proto protoreflect.FileDescriptor

var file_subscribe_house_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x2d, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x22, 0x3f, 0x0a,
	0x17, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x1a,
	0x0a, 0x18, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e,
	0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_subscribe_house_proto_rawDescOnce sync.Once
	file_subscribe_house_proto_rawDescData = file_subscribe_house_proto_rawDesc
)

func file_subscribe_house_proto_rawDescGZIP() []byte {
	file_subscribe_house_proto_rawDescOnce.Do(func() {
		file_subscribe_house_proto_rawDescData = protoimpl.X.CompressGZIP(file_subscribe_house_proto_rawDescData)
	})
	return file_subscribe_house_proto_rawDescData
}

var file_subscribe_house_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscribe_house_proto_goTypes = []any{
	(*SubscribeToHouseRequest)(nil),  // 0: home.SubscribeToHouseRequest
	(*SubscribeToHouseResponse)(nil), // 1: home.SubscribeToHouseResponse
}
var file_subscribe_house_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscribe_house_proto_init() }
func file_subscribe_house_proto_init() {
	if File_subscribe_house_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_subscribe_house_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeToHouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subscribe_house_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeToHouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subscribe_house_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscribe_house_proto_goTypes,
		DependencyIndexes: file_subscribe_house_proto_depIdxs,
		MessageInfos:      file_subscribe_house_proto_msgTypes,
	}.Build()
	File_subscribe_house_proto = out.File
	file_subscribe_house_proto_rawDesc = nil
	file_subscribe_house_proto_goTypes = nil
	file_subscribe_house_proto_depIdxs = nil
}
