// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// cacheSetter is an autogenerated mock type for the cacheSetter type
type cacheSetter struct {
	mock.Mock
}

// Set provides a mock function with given fields: key, value
func (_m *cacheSetter) Set(key string, value string) {
	_m.Called(key, value)
}

// newCacheSetter creates a new instance of cacheSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCacheSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *cacheSetter {
	mock := &cacheSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
