// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// emailSendler is an autogenerated mock type for the emailSendler type
type emailSendler struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: _a0, _a1, _a2
func (_m *emailSendler) SendEmail(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newEmailSendler creates a new instance of emailSendler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newEmailSendler(t interface {
	mock.TestingT
	Cleanup(func())
}) *emailSendler {
	mock := &emailSendler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
