// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FlatCreater is an autogenerated mock type for the FlatCreater type
type FlatCreater struct {
	mock.Mock
}

// CreateFlat provides a mock function with given fields: ctx, houseID, price, rooms
func (_m *FlatCreater) CreateFlat(ctx context.Context, houseID int, price int, rooms int) (int, error) {
	ret := _m.Called(ctx, houseID, price, rooms)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlat")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (int, error)); ok {
		return rf(ctx, houseID, price, rooms)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) int); ok {
		r0 = rf(ctx, houseID, price, rooms)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, houseID, price, rooms)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFlatCreater creates a new instance of FlatCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlatCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlatCreater {
	mock := &FlatCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
