// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "home-service/internal/models"
)

// FlatsByHouseGetter is an autogenerated mock type for the FlatsByHouseGetter type
type FlatsByHouseGetter struct {
	mock.Mock
}

// GetFlatsByHouseID provides a mock function with given fields: ctx, houseID, includeAll
func (_m *FlatsByHouseGetter) GetFlatsByHouseID(ctx context.Context, houseID int, includeAll bool) ([]models.Flat, error) {
	ret := _m.Called(ctx, houseID, includeAll)

	if len(ret) == 0 {
		panic("no return value specified for GetFlatsByHouseID")
	}

	var r0 []models.Flat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) ([]models.Flat, error)); ok {
		return rf(ctx, houseID, includeAll)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) []models.Flat); ok {
		r0 = rf(ctx, houseID, includeAll)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Flat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = rf(ctx, houseID, includeAll)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFlatsByHouseGetter creates a new instance of FlatsByHouseGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlatsByHouseGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlatsByHouseGetter {
	mock := &FlatsByHouseGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
