// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GetSubscriber is an autogenerated mock type for the GetSubscriber type
type GetSubscriber struct {
	mock.Mock
}

// GetSubscribers provides a mock function with given fields: ctx, houseID
func (_m *GetSubscriber) GetSubscribers(ctx context.Context, houseID int) ([]string, error) {
	ret := _m.Called(ctx, houseID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscribers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return rf(ctx, houseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, houseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, houseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetSubscriber creates a new instance of GetSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetSubscriber {
	mock := &GetSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
