// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "home-service/internal/models"
)

// HouseGetter is an autogenerated mock type for the HouseGetter type
type HouseGetter struct {
	mock.Mock
}

// GetHouse provides a mock function with given fields: ctx, houseID
func (_m *HouseGetter) GetHouse(ctx context.Context, houseID int) (models.House, error) {
	ret := _m.Called(ctx, houseID)

	if len(ret) == 0 {
		panic("no return value specified for GetHouse")
	}

	var r0 models.House
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.House, error)); ok {
		return rf(ctx, houseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.House); ok {
		r0 = rf(ctx, houseID)
	} else {
		r0 = ret.Get(0).(models.House)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, houseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHouseGetter creates a new instance of HouseGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHouseGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *HouseGetter {
	mock := &HouseGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
