// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HouseCreater is an autogenerated mock type for the HouseCreater type
type HouseCreater struct {
	mock.Mock
}

// CreateHouse provides a mock function with given fields: ctx, address, year, developer
func (_m *HouseCreater) CreateHouse(ctx context.Context, address string, year int, developer string) (int, error) {
	ret := _m.Called(ctx, address, year, developer)

	if len(ret) == 0 {
		panic("no return value specified for CreateHouse")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) (int, error)); ok {
		return rf(ctx, address, year, developer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) int); ok {
		r0 = rf(ctx, address, year, developer)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = rf(ctx, address, year, developer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHouseCreater creates a new instance of HouseCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHouseCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *HouseCreater {
	mock := &HouseCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
