// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// jetPusher is an autogenerated mock type for the jetPusher type
type jetPusher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: subsject, message
func (_m *jetPusher) Publish(subsject string, message []byte) error {
	ret := _m.Called(subsject, message)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(subsject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newJetPusher creates a new instance of jetPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newJetPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *jetPusher {
	mock := &jetPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
