// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeHouseServiceServer is an autogenerated mock type for the UnsafeHouseServiceServer type
type UnsafeHouseServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedHouseServiceServer provides a mock function with given fields:
func (_m *UnsafeHouseServiceServer) mustEmbedUnimplementedHouseServiceServer() {
	_m.Called()
}

// NewUnsafeHouseServiceServer creates a new instance of UnsafeHouseServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeHouseServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeHouseServiceServer {
	mock := &UnsafeHouseServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
