// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: api/auth/dummy-login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserType UserType `protobuf:"varint,1,opt,name=user_type,proto3,enum=auth.UserType" json:"user_type,omitempty"`
}

func (x *DummyLoginRequest) Reset() {
	*x = DummyLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auth_dummy_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginRequest) ProtoMessage() {}

func (x *DummyLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_dummy_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginRequest.ProtoReflect.Descriptor instead.
func (*DummyLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_dummy_login_proto_rawDescGZIP(), []int{0}
}

func (x *DummyLoginRequest) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_client
}

type DummyLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DummyLoginResponse) Reset() {
	*x = DummyLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auth_dummy_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyLoginResponse) ProtoMessage() {}

func (x *DummyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_dummy_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyLoginResponse.ProtoReflect.Descriptor instead.
func (*DummyLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_dummy_login_proto_rawDescGZIP(), []int{1}
}

func (x *DummyLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_auth_dummy_login_proto protoreflect.FileDescriptor

var file_api_auth_dummy_login_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79,
	0x2d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x11, 0x44,
	0x75, 0x6d, 0x6d, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2a,
	0x0a, 0x12, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e,
	0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_auth_dummy_login_proto_rawDescOnce sync.Once
	file_api_auth_dummy_login_proto_rawDescData = file_api_auth_dummy_login_proto_rawDesc
)

func file_api_auth_dummy_login_proto_rawDescGZIP() []byte {
	file_api_auth_dummy_login_proto_rawDescOnce.Do(func() {
		file_api_auth_dummy_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_auth_dummy_login_proto_rawDescData)
	})
	return file_api_auth_dummy_login_proto_rawDescData
}

var file_api_auth_dummy_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_auth_dummy_login_proto_goTypes = []any{
	(*DummyLoginRequest)(nil),  // 0: auth.DummyLoginRequest
	(*DummyLoginResponse)(nil), // 1: auth.DummyLoginResponse
	(UserType)(0),              // 2: auth.UserType
}
var file_api_auth_dummy_login_proto_depIdxs = []int32{
	2, // 0: auth.DummyLoginRequest.user_type:type_name -> auth.UserType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_auth_dummy_login_proto_init() }
func file_api_auth_dummy_login_proto_init() {
	if File_api_auth_dummy_login_proto != nil {
		return
	}
	file_api_auth_register_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_auth_dummy_login_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DummyLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auth_dummy_login_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DummyLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_auth_dummy_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_dummy_login_proto_goTypes,
		DependencyIndexes: file_api_auth_dummy_login_proto_depIdxs,
		MessageInfos:      file_api_auth_dummy_login_proto_msgTypes,
	}.Build()
	File_api_auth_dummy_login_proto = out.File
	file_api_auth_dummy_login_proto_rawDesc = nil
	file_api_auth_dummy_login_proto_goTypes = nil
	file_api_auth_dummy_login_proto_depIdxs = nil
}
