name: Gateway Service CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.4

    - name: Install dependencies
      run: cd gateway && go mod tidy

    - name: Run tests
      run: cd gateway && go test ./... -v

    - name: Generate test coverage report
      run: cd gateway && go test ./... -coverprofile=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: gateway/coverage.out
